name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v4.7.0
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Generate debug keystore
      run: |
        keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey \
          -keypass android -keyalg RSA -keysize 2048 -validity 10000 \
          -dname "CN=Android Debug,O=Android,C=US"

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Rename APK
      run: |
        APK_ORIG=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
        mv "$APK_ORIG" AE-Sticker.apk
        echo "APK_PATH=AE-Sticker.apk" >> $GITHUB_ENV

    - name: Verify APK Path
      run: |
        if [ ! -f "$APK_PATH" ]; then
          echo "❌ Error: APK not found at $APK_PATH";
          exit 1;
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AE-Sticker
        path: ${{ env.APK_PATH }}
